"""empty message

Revision ID: 1e070cb91c7a
Revises: 
Create Date: 2022-01-21 17:17:12.018717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e070cb91c7a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medical_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('diabetes', sa.Boolean(), nullable=False),
    sa.Column('uric_acid', sa.Boolean(), nullable=False),
    sa.Column('gastric_ulcers', sa.Boolean(), nullable=False),
    sa.Column('gastritis', sa.Boolean(), nullable=False),
    sa.Column('cholesterol', sa.Boolean(), nullable=False),
    sa.Column('triglycerides', sa.Boolean(), nullable=False),
    sa.Column('dairy_intolerance', sa.Boolean(), nullable=False),
    sa.Column('celiac', sa.Boolean(), nullable=False),
    sa.Column('obesity', sa.Boolean(), nullable=False),
    sa.Column('kidney_stones', sa.Boolean(), nullable=False),
    sa.Column('inflametion_of_the_colon', sa.Boolean(), nullable=False),
    sa.Column('heart_problems', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipes_name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description'),
    sa.UniqueConstraint('description'),
    sa.UniqueConstraint('recipes_name'),
    sa.UniqueConstraint('recipes_name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('email')
    )
    op.create_table('user_information',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=150), nullable=False),
    sa.Column('gender', sa.String(length=80), nullable=False),
    sa.Column('date_of_birth', sa.Integer(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('ailments', sa.Boolean(), nullable=False),
    sa.Column('exercises', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_recipes')
    op.drop_table('user_information')
    op.drop_table('user')
    op.drop_table('recipes')
    op.drop_table('medical_history')
    # ### end Alembic commands ###
