"""empty message

Revision ID: 33c0a58f9942
Revises: 
Create Date: 2022-02-01 23:58:45.560205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33c0a58f9942'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=150), nullable=False),
    sa.Column('gender', sa.String(length=80), nullable=False),
    sa.Column('date_of_birth', sa.String(length=25), nullable=False),
    sa.Column('exercises', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('medical__history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('diabetes', sa.String(length=10), nullable=False),
    sa.Column('uric_acid', sa.String(length=10), nullable=False),
    sa.Column('gastric_ulcers', sa.String(length=10), nullable=False),
    sa.Column('gastritis', sa.String(length=10), nullable=False),
    sa.Column('cholesterol', sa.String(length=10), nullable=False),
    sa.Column('triglycerides', sa.String(length=10), nullable=False),
    sa.Column('dairy_intolerance', sa.String(length=10), nullable=False),
    sa.Column('celiac', sa.String(length=10), nullable=False),
    sa.Column('obesity', sa.String(length=10), nullable=False),
    sa.Column('kidney_stones', sa.String(length=10), nullable=False),
    sa.Column('inflammation_of_the_colon', sa.String(length=10), nullable=False),
    sa.Column('heart_problems', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medical__history')
    op.drop_table('user')
    # ### end Alembic commands ###
