"""empty message

Revision ID: 8e70c7f01608
Revises: 2ac686209090
Create Date: 2022-01-29 20:42:16.835605

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8e70c7f01608'
down_revision = '2ac686209090'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medical__history', sa.Column('inflammation_of_the_colon', sa.String(length=10), nullable=False))
    op.drop_column('medical__history', 'inflametion_of_the_colon')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medical__history', sa.Column('inflametion_of_the_colon', mysql.VARCHAR(length=10), nullable=False))
    op.drop_column('medical__history', 'inflammation_of_the_colon')
    # ### end Alembic commands ###
